name: CI/CD Pipeline             # name of workflow

on:                             # to trigger automatically to run on main or develop branch 
  push:
    branches:
      - main
      - develop
  pull_request:                     # when the Pull Request is open , trigger is on to  the targets are main or develop branch 
    branches:
      - main
      - develop

jobs:                                      # Defines a list of tasks 
  build:                                   # job name 
    runs-on: ubuntu-latest                 # works on ubunto OS

    steps:                                     # Inside of steps , ecery line executes a command in CI/CD pipeline 
      - name: Set Environment Variables
        run: echo "MY_PASS=${{ secrets.MY_PASS }}" >> "$GITHUB_ENV"
      
      #- name: Change to Repository Directory       #the workflow runs inside the correct directory where package.json is located.
      #  run: cd $GITHUB_WORKSPACE

      - name: Checkout Repository
        uses: actions/checkout@v3               # Download your latest repository to  machine firstly 

      # **For Python**
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies                     # Install required packages 
        run: pip install -r requirements.txt pytest

      - name: Run Tests                                # testing the code 
        run: pytest

      - name: Build Application                  # builds rpoject 
        run: python setup.py build


