name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest               
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  ##clones githup repository onto ubuntu machine because of workflow can reach the code 

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}            ## login using docker_username and pass which is acces key 
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build from dockerfile and Push Docker Image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .   ##build the Docker image from the locaation of dockerfile
          push: true    ## push the built image to Docker Hub.
          tags: aslihanozhan/repoasli:latest
